# SPDX-License-Identifier: GPL-2.0
#
# Makefile for ALSA
# Copyright (c) 2001 by Jaroslav Kysela <perex@perex.cz>
#

snd-avb-objs := msrp.o avdecc.o avtp.o avb_common.o avb.o

obj-$(CONFIG_SND_AVB) += snd-avb.o